// User Action Types
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_ERROR = "USER_REGISTER_ERROR";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";

export const USER_PROFILE_REQUEST = "USER_PROFILE_REQUEST";
export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS";
export const USER_PROFILE_ERROR = "USER_PROFILE_ERROR";

export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_ERROR = "USER_UPDATE_ERROR";

export const USER_ADDRESS_SAVE_REQUEST = "USER_ADDRESS_SAVE_REQUEST";
export const USER_ADDRESS_SAVE_SUCCESS = "USER_ADDRESS_SAVE_SUCCESS";
export const USER_ADDRESS_SAVE_ERROR = "USER_ADDRESS_SAVE_ERROR";

export const USER_ADDRESS_DATA_REQUEST = "USER_ADDRESS_DATA_REQUEST";
export const USER_ADDRESS_DATA_SUCCESS = "USER_ADDRESS_DATA_SUCCESS";
export const USER_ADDRESS_DATA_ERROR = "USER_ADDRESS_DATA_ERROR";

export const USER_ADDRESS_ID_REQUEST = "USER_ADDRESS_ID_REQUEST";
export const USER_ADDRESS_ID_SUCCESS = "USER_ADDRESS_ID_SUCCESS";
export const USER_ADDRESS_ID_ERROR = "USER_ADDRESS_ID_ERROR";

export const USER_LOGOUT_REQUEST = "USER_LOGOUT_REQUEST";

export const USER_SESSION_CHECK = "USER_SESSION_CHECK";

// Products Action Types
export const PRODUCT_CREATE_REQUEST = "PRODUCT_CREATE_REQUEST";
export const PRODUCT_CREATE_SUCCESS = "PRODUCT_CREATE_SUCCESS";
export const PRODUCT_CREATE_ERROR = "PRODUCT_CREATE_ERROR";

export const PRODUCTS_FETCH_REQUEST = "PRODUCTS_FETCH_REQUEST";
export const PRODUCTS_FETCH_SUCCESS = "PRODUCTS_FETCH_SUCCESS";
export const PRODUCTS_FETCH_ERROR = "PRODUCTS_FETCH_ERROR";

export const PRODUCT_FETCH_REQUEST = "PRODUCT_FETCH_REQUEST";
export const PRODUCT_FETCH_SUCCESS = "PRODUCT_FETCH_SUCCESS";
export const PRODUCT_FETCH_ERROR = "PRODUCT_FETCH_ERROR";

export const PRODUCT_UPDATE_REQUEST = "PRODUCT_UPDATE_REQUEST";
export const PRODUCT_UPDATE_SUCCESS = "PRODUCT_UPDATE_SUCCESS";
export const PRODUCT_UPDATE_ERROR = "PRODUCT_UPDATE_ERROR";

// Categories Action Types
export const CATEGORIES_GET_REQUEST = "CATEGORIES_GET_REQUEST";
export const CATEGORIES_GET_SUCCESS = "CATEGORIES_GET_SUCCESS";
export const CATEGORIES_GET_ERROR = "CATEGORIES_GET_ERROR";

export const CATEGORY_GET_REQUEST = "CATEGORY_GET_REQUEST";
export const CATEGORY_GET_SUCCESS = "CATEGORY_GET_SUCCESS";
export const CATEGORY_GET_ERROR = "CATEGORY_GET_ERROR";

export const CATEGORY_CREATE_REQUEST = "CATEGORY_CREATE_REQUEST";
export const CATEGORY_CREATE_SUCCESS = "CATEGORY_CREATE_SUCCESS";
export const CATEGORY_CREATE_ERROR = "CATEGORY_CREATE_ERROR";

export const CATEGORY_UPDATE_REQUEST = "CATEGORY_UPDATE_REQUEST";
export const CATEGORY_UPDATE_SUCCESS = "CATEGORY_UPDATE_SUCCESS";
export const CATEGORY_UPDATE_ERROR = "CATEGORY_UPDATE_ERROR";

export const CATEGORY_DELETE_START = "CATEGORY_DELETE_START";

// Cart Action Types
export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
export const CART_REDUCE_QUANTITY = "CART_REDUCE_QUANTITY";
export const CART_CLEAR = "CART_CLEAR";

// Order Actions
export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_ERROR = "ORDER_CREATE_ERROR";

export const USER_ORDERS_REQUEST = "USER_ORDERS_REQUEST";
export const USER_ORDERS_SUCCESS = "USER_ORDERS_SUCCESS";
export const USER_ORDERS_ERROR = "USER_ORDERS_ERROR";

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_ERROR = "ORDER_DETAILS_ERROR";

export const MPESA_STK_REQUEST = "MPESA_STK_REQUEST";
export const MPESA_STK_SUCCESS = "MPESA_STK_SUCCESS";
export const MPESA_STK_ERROR = "MPESA_STK_ERROR";
